exchanges:
    kraken:
        api_key: 'm5hS6adPc0u65GsNxqk6c0wkAaBWM+eHzTq5QPtMrn7j4AOd6ZouqlRt'    # Ihr Kraken API Key
        secret: 'l7e+BeQEURFa9Vkaz1gzu/F2FGIeAkdhBCLZrYFrAWOIk3E6AIfQcn9jdl/W+i5L/3s81RSWhFvXzs0ET8+//w=='   # Hier brauchen wir Ihren Kraken Secret Key

sentiment_params:
    reddit:
        client_id: 'RbCqjOq25eY7oRFprkXd8g'
        client_secret: '4SHq2fG_nbq0VLjSQwFBpLN7RhoAPA'
        user_agent: 'script:crypto_trading_bot:v1.0 (by /u/MasterpieceWaste2470)'


apis:
    news_api_key: "915c3d2e14ad4c46be289bf26206e293"
    alphavantage:
       api_key: "M53240NVJOJA37V8"
    etherscan:
       api_key: "IWCXI3JUF1PJHVMD1KC5UQ5Q7PX1XVJJB4"

pushover:
    user_key: "uthrm412v5z5gquxv8sksq8gzmjw41"
    api_token: "adxfbyf9ua4mw5rbs8dzsnvgvc91bs"



risk_params:
    max_position_size: 0.001
    stop_loss_pct: 0.01
    take_profit_pct: 0.02
    max_daily_trades: 3


