# Test-Konfigurationsdatei für den Trading-Bot
exchanges:
  kraken:
    api_key: "test_api_key"  # Test API-Schlüssel (Dummy)
    secret: "test_api_secret"  # Test API-Secret (Dummy)

trading_params:
  paper_trading: true  # Paper-Trading aktiviert (kein echtes Geld)
  base_currency: "BTC"
  quote_currency: "USD"
  trade_amount: 0.01  # Testbetrag pro Trade
  max_trades_per_day: 3  # Limit für Testtrades

indicators:
  rsi_period: 14
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  bollinger_period: 20

risk_management:
  stop_loss: 0.02  # 2% Stop-Loss für Tests
  take_profit: 0.05  # 5% Take-Profit für Tests

sentiment_params:
  use_reddit: true
  use_news: false
  reddit:
    client_id: "test_reddit_client_id"
    client_secret: "test_reddit_client_secret"
    user_agent: "test_bot_agent"

logging:
  level: "INFO"  # Logging-Level für Tests
